[project]
name = "neofinesse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shan", email = "92211264+sannidhyasahoo@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "pydantic>=2.13.5",
]

[project.scripts]
neofinesse = "neofinesse:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]
