from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field

from neofinesse.ai_investigation.evidence_pack import EvidenceItem
from neofinesse.ai_investigation.models import ConflictItem
from neofinesse.investigation.models import CauseType, Hypothesis, InvestigationAuditRecord, InvestigationStatus


class AgentInvestigationStatus(str, Enum):
    SUFFICIENT = "SUFFICIENT"
    NEEDS_EVIDENCE = "NEEDS_EVIDENCE"
    ESCALATE = "ESCALATE"


class ToolRequest(BaseModel):
    """Structured tool invocation request generated by the AI agent."""

    model_config = ConfigDict(extra="forbid")

    request_id: str = Field(description="Unique deterministic tool request ID (e.g. REQ-1)")
    tool: str = Field(description="Name of the registered tool to invoke")
    arguments: Dict[str, Any] = Field(description="Typed arguments matching the tool schema")
    reason: str = Field(description="Financial rationale for requesting this evidence")


class ToolResult(BaseModel):
    """Structured output returned from a validated investigation tool execution."""

    model_config = ConfigDict(extra="forbid")

    request_id: str
    tool: str
    success: bool
    output: Any = Field(description="Structured tool output (e.g. status, records, transition history)")
    evidence_items: List[EvidenceItem] = Field(default_factory=list, description="New evidence items generated by tool")
    error: Optional[str] = None


class AgentHypothesisProposal(BaseModel):
    """Hypothesis proposed by the agent for verification."""

    model_config = ConfigDict(extra="forbid")

    hypothesis_id: str
    cause_type: CauseType
    evidence_ids: List[str] = Field(description="Must reference valid evidence IDs currently in investigation state")
    claimed_explained_amount: int = Field(description="Claimed explained amount in integer paise")
    recalculated_explained_amount: Optional[int] = None
    reasoning: str
    missing_evidence: List[str] = Field(default_factory=list)
    conflicts: List[ConflictItem] = Field(default_factory=list)
    assumptions: List[str] = Field(default_factory=list)


class AgentRoundResponse(BaseModel):
    """Complete structured response returned by the AI agent for an investigation round."""

    model_config = ConfigDict(extra="forbid")

    status: AgentInvestigationStatus
    hypotheses: List[AgentHypothesisProposal] = Field(default_factory=list)
    investigation_requests: List[ToolRequest] = Field(default_factory=list)
    recommended_hypothesis_id: Optional[str] = None
    conflicts: List[ConflictItem] = Field(default_factory=list)
    missing_evidence: List[str] = Field(default_factory=list)
    reasoning: str


class InvestigationBudget(BaseModel):
    """Configurable resource and recursion constraints for agentic investigation."""

    model_config = ConfigDict(extra="forbid")

    max_investigation_rounds: int = Field(default=3, ge=1, le=10)
    max_tool_calls: int = Field(default=5, ge=1, le=20)
    max_evidence_records: int = Field(default=50, ge=1, le=200)


class AgenticInvestigationResult(BaseModel):
    """Final output of an agentic investigation containing audit trail and verification outcome."""

    model_config = ConfigDict(extra="forbid")

    case_id: str
    settlement_id: str
    target_variance: int  # in paise
    final_status: InvestigationStatus
    winning_hypothesis: Optional[Hypothesis] = None
    explained_amount: int = 0
    unexplained_amount: int = 0
    total_rounds: int = 1
    total_tool_calls: int = 0
    total_evidence_collected: int = 0
    budget_exhausted: bool = False
    revisions_count: int = 0
    audit_record: InvestigationAuditRecord
    state_snapshot: Dict[str, Any] = Field(default_factory=dict)
    investigation_latency_ms: float = 0.0
