from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field

from neofinesse.ai_investigation.evidence_pack import EvidenceItem
from neofinesse.ai_investigation.models import ConflictItem
from neofinesse.investigation.models import CauseType, Hypothesis, InvestigationAuditRecord, InvestigationStatus


class AgentInvestigationStatus(str, Enum):
    SUFFICIENT = "SUFFICIENT"
    NEEDS_EVIDENCE = "NEEDS_EVIDENCE"
    ESCALATE = "ESCALATE"


class FailureType(str, Enum):
    NONE = "NONE"
    FALSE_CLOSURE = "FALSE_CLOSURE"
    FALSE_ESCALATION = "FALSE_ESCALATION"
    WRONG_PARTIAL_ATTRIBUTION = "WRONG_PARTIAL_ATTRIBUTION"
    OTHER = "OTHER"


class ToolRequest(BaseModel):
    """Structured tool invocation request generated by the AI agent."""

    model_config = ConfigDict(extra="forbid")

    request_id: str = Field(description="Unique deterministic tool request ID (e.g. REQ-1)")
    tool: str = Field(description="Name of the registered tool to invoke")
    arguments: Dict[str, Any] = Field(description="Typed arguments matching the tool schema")
    reason: str = Field(description="Financial rationale for requesting this evidence")


class ToolResult(BaseModel):
    """Structured output returned from a validated investigation tool execution."""

    model_config = ConfigDict(extra="forbid")

    request_id: str
    tool: str
    success: bool
    output: Any = Field(description="Structured tool output (e.g. status, records, transition history)")
    evidence_items: List[EvidenceItem] = Field(default_factory=list, description="New evidence items generated by tool")
    error: Optional[str] = None


class ToolRequestAuditRecord(BaseModel):
    """Audited log entry for a specific tool request across benchmark scenarios."""

    model_config = ConfigDict(extra="forbid")

    request_id: str
    scenario_id: str
    tool: str
    arguments: Dict[str, Any]
    is_valid: bool
    is_duplicate: bool
    rejection_reason: Optional[str] = None
    executed: bool
    execution_error: Optional[str] = None


class AgentHypothesisProposal(BaseModel):
    """Hypothesis proposed by the agent for verification."""

    model_config = ConfigDict(extra="forbid")

    hypothesis_id: str
    cause_type: CauseType
    evidence_ids: List[str] = Field(description="Must reference valid evidence IDs currently in investigation state")
    claimed_explained_amount: int = Field(description="Claimed explained amount in integer paise")
    recalculated_explained_amount: Optional[int] = None
    reasoning: str
    missing_evidence: List[str] = Field(default_factory=list)
    conflicts: List[ConflictItem] = Field(default_factory=list)
    assumptions: List[str] = Field(default_factory=list)


class AgentRoundResponse(BaseModel):
    """Complete structured response returned by the AI agent for an investigation round."""

    model_config = ConfigDict(extra="forbid")

    status: AgentInvestigationStatus
    hypotheses: List[AgentHypothesisProposal] = Field(default_factory=list)
    investigation_requests: List[ToolRequest] = Field(default_factory=list)
    recommended_hypothesis_id: Optional[str] = None
    conflicts: List[ConflictItem] = Field(default_factory=list)
    missing_evidence: List[str] = Field(default_factory=list)
    reasoning: str


class InvestigationBudget(BaseModel):
    """Configurable resource and recursion constraints for agentic investigation."""

    model_config = ConfigDict(extra="forbid")

    max_investigation_rounds: int = Field(default=3, ge=1, le=10)
    max_tool_calls: int = Field(default=5, ge=1, le=20)
    max_evidence_records: int = Field(default=50, ge=1, le=200)


class AgenticInvestigationResult(BaseModel):
    """Final output of an agentic investigation containing audit trail and verification outcome."""

    model_config = ConfigDict(extra="forbid")

    case_id: str
    settlement_id: str
    target_variance: int  # in paise
    final_status: InvestigationStatus
    winning_hypothesis: Optional[Hypothesis] = None
    explained_amount: int = 0
    unexplained_amount: int = 0
    total_rounds: int = 1
    total_tool_calls: int = 0
    total_evidence_collected: int = 0
    budget_exhausted: bool = False
    termination_reason: str = "COMPLETED"
    revisions_count: int = 0
    audit_record: InvestigationAuditRecord
    state_snapshot: Dict[str, Any] = Field(default_factory=dict)
    investigation_latency_ms: float = 0.0
    orchestration_latency_ms: float = 0.0
    llm_latency_ms: float = 0.0
    tool_latency_ms: float = 0.0
    llm_provider: str = "mock"
    llm_model: str = "mock-agent-v1"
    llm_tokens_used: Optional[int] = None


class CategoryEvaluationMetrics(BaseModel):
    """Metrics breakdown for a specific category of investigation scenarios with explicit zero-denominator handling."""

    model_config = ConfigDict(extra="forbid")

    category_name: str
    total_scenarios: int
    correct_terminal_decision_rate_pct: float
    phase5_correct_terminal_decision_rate_pct: float
    phase6_correct_terminal_decision_rate_pct: float
    observed_resolution_rate_pct: float
    phase5_observed_resolution_rate_pct: float
    phase6_observed_resolution_rate_pct: float
    false_closure_rate_pct: Optional[float] = None
    phase5_false_closure_rate_pct: Optional[float] = None
    phase6_false_closure_rate_pct: Optional[float] = None
    false_escalation_rate_pct: Optional[float] = None
    phase5_false_escalation_rate_pct: Optional[float] = None
    phase6_false_escalation_rate_pct: Optional[float] = None
    honest_exception_rate_pct: Optional[float] = None
    partial_attribution_accuracy_pct: Optional[float] = None
    local_pipeline_latency_mean_ms: float
    local_pipeline_latency_median_ms: float
    local_pipeline_latency_min_ms: float
    local_pipeline_latency_max_ms: float

    @property
    def actual_resolution_rate_pct(self) -> float:
        return self.observed_resolution_rate_pct


class AgenticBenchmarkScorecard(BaseModel):
    """Audited benchmark scorecard with rigorous mathematical definitions and ground-truth anchors."""

    model_config = ConfigDict(extra="forbid")

    total_scenarios_evaluated: int

    # Terminal Decision Matching (Matches Expected Outcome)
    correct_terminal_decision_rate_pct: float
    phase5_correct_terminal_decision_rate_pct: float
    phase6_correct_terminal_decision_rate_pct: float
    phase7_correct_terminal_decision_rate_pct: float
    oracle_correct_terminal_decision_rate_pct: float
    always_escalate_baseline_accuracy_pct: float = 47.8

    # Observed Financial Status Rates (RESOLVED or VALID_DELAYED_CREDIT)
    observed_resolution_rate_pct: float
    phase5_observed_resolution_rate_pct: float
    phase6_observed_resolution_rate_pct: float
    phase7_observed_resolution_rate_pct: float
    escalation_rate_pct: float
    partial_resolution_rate_pct: float

    # Safety & Error Classification Metrics
    phase5_false_closure_rate_pct: Optional[float] = None
    phase6_false_closure_rate_pct: Optional[float] = None
    phase7_false_closure_rate_pct: Optional[float] = None
    phase5_false_escalation_rate_pct: Optional[float] = None
    phase6_false_escalation_rate_pct: Optional[float] = None
    phase7_false_escalation_rate_pct: Optional[float] = None
    honest_exception_rate_pct: Optional[float] = None
    partial_attribution_accuracy_pct: Optional[float] = None

    # Investigation Efficiency & Tool Governance
    avg_investigation_rounds: float
    median_investigation_rounds: float
    avg_tool_calls: float
    median_tool_calls: float
    tool_request_validity_pct: float
    invalid_request_rejection_rate_pct: Optional[float] = None
    tool_safety_rate_pct: float
    duplicate_request_rate_pct: float
    budget_compliance_rate_pct: float
    budget_violations_count: int
    hallucination_rejection_pct: float
    hypothesis_revision_accuracy_pct: Optional[float] = None
    tool_selection_accuracy_pct: Optional[float] = None
    evidence_acquisition_success_pct: Optional[float] = None
    hypothesis_revisions_count: int

    # Causal Evidence Efficiency (Ground-Truth Based)
    evidence_efficiency_mean_pct: Optional[float] = None
    evidence_efficiency_median_pct: Optional[float] = None
    evidence_efficiency_p25_pct: Optional[float] = None
    evidence_efficiency_p75_pct: Optional[float] = None
    evidence_efficiency_min_pct: Optional[float] = None
    evidence_efficiency_max_pct: Optional[float] = None

    # Local Pipeline Execution Latency (Mock Environment)
    local_pipeline_latency_mean_ms: float
    local_pipeline_latency_median_ms: float
    local_pipeline_latency_min_ms: float
    local_pipeline_latency_max_ms: float

    # Category-Specific Metrics & Detailed Scenario Results
    category_metrics: Dict[str, CategoryEvaluationMetrics] = Field(default_factory=dict)
    scenario_results: List[Dict[str, Any]] = Field(default_factory=list)
    tool_requests_audit: List[ToolRequestAuditRecord] = Field(default_factory=list)

    @property
    def actual_resolution_rate_pct(self) -> float:
        return self.observed_resolution_rate_pct
